seed: 1234
torch_home: 

method:  FaceForensics_c23 
compression: c23
checkpoints_dir: checkpoints
name: ${model.label}_${model.name}
exam_dir: ./checkpoints/${model.label}_${model.name}
is_aligned: True
align_type: com 

transform_params:
  image_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

train:
  batch_size: 64
  num_workers: 16
  print_info_step_freq: 10
  save_model_interval: 10
  max_epoches: 100
  use_warmup: False
  warmup_epochs: 0
  max_cdfauc: 0.0
  max_dfdcauc: 0.0

  dataset:
    name: Image_Flow_SBI_dataset
    params:
      root: /home/guozonghui/data1/project/01-FFD/datasets_processed/
      method: ${method}
      split: train
      num_segments: 8 #8
      num_segments_flow: 12
      cutout: True #True
      is_sbi: False
      image_size: ${transform_params.image_size}
      upsample_real: 0

test:
  batch_size: 2
  num_workers: ${train.num_workers}
  dataset:
    name: Image_dataset_random_rgbwflow_s1_test
    params:
            #root: ../datasets_processed_8frames/
      root: /home/guozonghui/data1/project/01-FFD/datasets_processed_8frames/
      method:  ${method}  #FF-ALL 
      split: test
      num_segments: 32
      num_segments_flow: 10
      cutout: True
      is_sbi: False
      image_size: ${transform_params.image_size}

final_test:
  batch_size: 2
  num_workers: ${test.num_workers}
  dataset:
    name: Image_dataset_random_rgbwflow_s1_test
    params:
            #root: ../datasets_processed_8frames/
      root: /home/guozonghui/data1/project/01-FFD/datasets_processed_8frames/
      methods: ['ALL']
      method: ALL
      split: test
      is_sbi: False
      num_segments: 32
      num_segments_flow: 10
      image_size: ${transform_params.image_size}

model:
  name:  BEiT_Flow_AttnAdapter_SBI_v3
  label:  Stage1
  backbone: ${model.name}
  params:
    num_segments: ${train.dataset.params.num_segments}
    num_segments_flow: ${train.dataset.params.num_segments_flow}
    num_segments_1: ${test.dataset.params.num_segments}
    num_segments_flow_1: ${test.dataset.params.num_segments_flow}
  #   network: vit_base_patch16_224
  #   pretrained_path: './pretrained_weight/B_16-i1k-300ep-lr_0.001-aug_strong2-wd_0.1-do_0.1-sd_0.1--imagenet2012-steps_20k-lr_0.01-res_224.npz'
  #   image_size: ${transform_params.image_size}
    embd_dim: 768
  resume:
  only_resume_model: False


optimizer:
  type: N #SAM
  name: lamb #AdamW #Adam  # SAM   #Adam
  params:
    lr: 5e-5
    opt: ${optimizer.name}
    weight_decay:  0.05  #1.0e-5
    momentum: 0.9
    clip_mode: norm
    layer_decay: .75

loss:
  name: CrossEntropyLoss
  params:

scheduler:
  sched: cosine
  lr: ${optimizer.params.lr}
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  lr_cycle_mul: 1.0
  lr_cycle_decay: 0.5
  lr_cycle_limit: 1
  lr_k_decay: 1.0
  warmup_lr: 1e-6
  min_lr: 1e-5
  epochs: ${train.max_epoches}
  warmup_epochs: 1
  cooldown_epochs: 0 #1 #5
